name: cuvs_binary_ivf_flat
groups:
  openai_5m_nlist_256:
    build:
      nlist: [256]
      niter: [25]
      max_train_points_per_centroid: [64]
      sampling_seed: [42]
    search:
      nprobe: [1, 2, 4, 5, 8, 16, 32, 64, 128, 256]
  openai_5m_nlist_1024:
    build:
      nlist: [1024]
      niter: [25]
      max_train_points_per_centroid: [64]
      sampling_seed: [42]
    search:
      nprobe: [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 1024]
  openai_5m_nlist_4096:
    build:
      nlist: [4096]
      niter: [25]
      max_train_points_per_centroid: [64]
      sampling_seed: [42]
    search:
      nprobe: [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
  openai_5m_nlist_16384:
    build:
      nlist: [16384]
      niter: [25]
      max_train_points_per_centroid: [64]
      sampling_seed: [42]
    search:
      nprobe: [1, 2, 4, 5, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
