/*
 * Copyright (c) 2024, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "../../../core/nvtx.hpp"
#include "factory.cuh"
#include "sample_filter_utils.cuh"
#include "search_plan.cuh"
#include "search_single_cta_inst.cuh"

#include <raft/core/device_mdspan.hpp>
#include <raft/core/host_mdspan.hpp>
#include <raft/core/resource/cuda_stream.hpp>
#include <raft/core/resources.hpp>

#include <cuvs/distance/distance.hpp>

#include <cuvs/neighbors/cagra.hpp>

// TODO: Fix these when ivf methods are moved over
#include "../../ivf_common.cuh"
#include "../../ivf_pq/ivf_pq_search.cuh"
#include <cuvs/neighbors/common.hpp>

// TODO: This shouldn't be calling spatial/knn apis
#include "../ann_utils.cuh"

#include <rmm/cuda_stream_view.hpp>



#include <unistd.h>
#include <iostream>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <cstdint>
#include <algorithm>
#include <unordered_set>
#include <assert.h>
#include <boost/dynamic_bitset.hpp>
#include <omp.h>
#include <cuda_runtime.h>
#include <cub/cub.cuh>
#include "parANN.h"
#include "utils/utils.h"
#include "utils/timer.h"
#include <chrono>

#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#define MAX_R 64 // Max. node degree supported

// File name suffixes of various o/p files generated by DiskANN Graph construction (Vamana)
#define PQ_PIVOTS_FILE_SUFFIX "_pq_pivots.bin"
#define PQ_COMPRESSEDVECTORS_FILE_SUFFIX "_pq_compressed.bin"
#define PQ_CHUNK_OFFSETS_FILE_SUFFIX "_pq_pivots.bin_chunk_offsets.bin"
#define PQ_CENTROID_FILE_SUFFIX "_pq_pivots.bin_centroid.bin"
#define GRAPH_INDEX_FILE_SUFFIX "_disk.bin"
#define GRAPH_INDEX_METADATA_FILE_SUFFIX "_disk_metadata.bin" // This is explicitly generated by running BANG script bang_preprocess.py

// The size of Bloom Filter.
#define BF_ENTRIES  399887U    	 // BF is maintained per query (prime number close to 4k)
const unsigned BF_MEMORY = (BF_ENTRIES & 0xFFFFFFFC) + sizeof(unsigned); // 4-byte mem aligned size for actual allocation

// Indicates static upper bound on search iterations performed
// uMAX_PARENTS_PERQUERY is the limit determined dynamically based on worklist length
// a #define is needed for shared memory allocation and the dynamic limit cannot be used directly
#define MAX_PARENTS_PERQUERY  (L+50) 
									
// Per query, nly one Candidate (Parent) is send from GPU to CPU  to fetch its neighbours from the Graph Index.
// In future, we could use multiple Parents.
#define SIZEPARENTLIST  (1+1) // one to indicate present/absent and other the actual parent ID

// Capabilities
#define ENABLE_GPU_STATS 		0x00000001

#define _DBG_BOUNDS

using namespace std;
namespace cuvs::neighbors::experimental::bang::detail {
template<typename T>
void bang_load(char* indexfile_path_prefix)
{
	string diskann_Generatedfiles_path = std::string(indexfile_path_prefix);
	string pqTable_file = diskann_Generatedfiles_path +  PQ_PIVOTS_FILE_SUFFIX;//string(argv[1]); // Pivot files
	string compressedVector_file = diskann_Generatedfiles_path + PQ_COMPRESSEDVECTORS_FILE_SUFFIX;//string(argv[2]);
	string graphAdjListAndFP_file = diskann_Generatedfiles_path + GRAPH_INDEX_FILE_SUFFIX;//string(argv[3]);
	string graphMetadata_file = diskann_Generatedfiles_path + GRAPH_INDEX_METADATA_FILE_SUFFIX;//string(argv[3]);
    string chunkOffsets_file = diskann_Generatedfiles_path + PQ_CHUNK_OFFSETS_FILE_SUFFIX ;//string(argv[5]);
	string centroid_file = diskann_Generatedfiles_path + PQ_CENTROID_FILE_SUFFIX;////string(argv[2]);

	// Check if files exist
	ifstream in1(pqTable_file, std::ios::binary);
	if(!in1.is_open()){
		printf("Error.. Could not open the PQ Pivots File: %s", pqTable_file.c_str() );
		return;
	}
	cout << pqTable_file << endl;
	ifstream in2(compressedVector_file, std::ios::binary);
	if(!in2.is_open()){
		printf("Error.. Could not open the PQ Compressed Vectors File: %s", compressedVector_file.c_str() );
		return;
	}
	cout << compressedVector_file<< endl;

	ifstream in3(graphAdjListAndFP_file, std::ios::binary);
	if(!in3.is_open()){
		printf("Error.. Could not open the Graph Index File: %s", graphAdjListAndFP_file.c_str());
		return;
	}
	cout << graphAdjListAndFP_file<< endl;

	// Reading the Graph Metadata File
	GraphMedataData objGrapMetaData;
	ifstream in5(graphMetadata_file, std::ios::binary);
	if(!in5.is_open()){
		printf("Error.. Could not open the Metadata File: %s\n", graphMetadata_file.c_str());
		return;
	}

	// Load Graph Metadata first
	in5.read((char*)&objGrapMetaData, sizeof(GraphMedataData));
	cout << "Metadata : " << objGrapMetaData.ullMedoid << ", " << objGrapMetaData.ulluIndexEntryLen  << ", " << objGrapMetaData.uDatatype  <<
	", " << objGrapMetaData.uDim << ", " << objGrapMetaData.uDegree << ", " << objGrapMetaData.uDatasetSize << endl;

	objIndexLoad.MEDOID = objGrapMetaData.ullMedoid;
	objIndexLoad.D = objGrapMetaData.uDim;;
	objIndexLoad.R = objGrapMetaData.uDegree;
	objIndexLoad.N = objGrapMetaData.uDatasetSize;
	objIndexLoad.ullIndex_Entry_LEN = objGrapMetaData.ulluIndexEntryLen;

	// Loading PQTable (binary)
	float *pqTable = NULL;
	pqTable = (float*) malloc(sizeof(float) * (256 * objIndexLoad.D)); // Contains pivot coordinates
	if (NULL == pqTable)
	{
		printf("Error.. Malloc failed PQ Table\n");
		return;
	}

	in1.seekg(8);
	in1.read((char*)pqTable,sizeof(float)*256*objIndexLoad.D);
	in1.close();

	// Loading PQ Compressed Vector (binary)
	unsigned int N = 0;
	in2.read((char*)&N, sizeof(int));
	cout << "No of points in Dataset = " << N	 << endl;

	unsigned int uChunks = 0;
	in2.read((char*)&uChunks, sizeof(int));
	cout << "# PQ Chunks = " << uChunks << endl;
	objIndexLoad.uChunks = uChunks;

	uint8_t* compressedVectors = NULL;
	compressedVectors = (uint8_t*) malloc(sizeof(uint8_t) * uChunks * N);

	if (NULL == compressedVectors)
	{
		printf("Error.. Malloc failed for Compressed Vectors\n");
		return;
	}

	in2.read((char*)compressedVectors, sizeof(uint8_t)*N*uChunks);
	in2.close();

	// To reduce Peak Host memory usage, loading compressed vectors to CPU and transferring to GPU and releasing host memory
	uint8_t* d_compressedVectors = NULL;
	gpuErrchk(cudaMalloc(&d_compressedVectors, sizeof(uint8_t) * N * uChunks)); 	//100M*100 ~10GB
	gpuErrchk(cudaMemcpy(d_compressedVectors, compressedVectors, (unsigned long long)(sizeof(uint8_t) * (unsigned long long)(uChunks)*N),
	cudaMemcpyHostToDevice));
	objIndexLoad.d_compressedVectors = d_compressedVectors;
	free(compressedVectors);
	compressedVectors = NULL;
	printf("Transferring Compressed Vectors done\n");

	// Load the Vamana(DiskANN) Graph Index
	uint8_t* pIndex = NULL;
	off_t size_indexfile = caclulate_filesize(graphAdjListAndFP_file.c_str());

	pIndex = (uint8_t*)malloc(size_indexfile);
	if (NULL == pIndex)
	{
		printf("Error.. Malloc failed for Graph\n");
		return;
	}
	objIndexLoad.pIndex = pIndex;
	objIndexLoad.size_indexfile = size_indexfile;
	int nRetIndex = mlock(pIndex, sizeof(size_indexfile));
	
	if (nRetIndex)
		perror("Index File");
	log_message("Index Load Started");
	in3.read((char*)pIndex, size_indexfile);
	log_message("Index Load Done");
	in3.close();

	// Loading chunk offsets
	unsigned n_chunks = uChunks;
	unsigned *chunksOffset = (unsigned*) malloc(sizeof(unsigned) * (n_chunks+1));
	uint64_t numr = n_chunks + 1;
	uint64_t numc = 1;

	load_bin<uint32_t>(chunkOffsets_file, chunksOffset, numr, numc);	//Import the chunkoffset file

	// Loading centroid coordinates
	float* centroid = nullptr;
	load_bin<float>(centroid_file, centroid, numr, numc);				//Import centroid from centroid file

	// GroundTruth loading done later

	// Sanity test start
	// to see if the Index file was loaded properly
	// Read the first and last neighbour
	unsigned* puNeighbour = NULL; // Very first neighbour
	unsigned* puNeighbour1 = NULL; // Very Last neighbour
	unsigned *puNumNeighbours = NULL;
	unsigned *puNumNeighbours1 = NULL;

	// First neighbour calculation
	puNumNeighbours = (unsigned*)(pIndex+((objIndexLoad.ullIndex_Entry_LEN*0)+ (sizeof(T)*objIndexLoad.D) ));
	puNeighbour = puNumNeighbours + 1;

	// Last neighbour calculation
	puNumNeighbours1 = (unsigned*)(pIndex + ( (objIndexLoad.ullIndex_Entry_LEN * (objIndexLoad.N-1)) + (sizeof(T)*objIndexLoad.D) )) ;
	puNeighbour1 = puNumNeighbours1 + (*puNumNeighbours1) ;
	// Print the first and last neighbour in AdjList
	printf("%u \t %u\n", *puNeighbour, *puNeighbour1);

	assert (*puNeighbour <= objIndexLoad.N);
	assert (*puNeighbour1 <= objIndexLoad.N);
	// Sanity test end
	
	cout << "Graph Medoid is : " << objIndexLoad.MEDOID << "\t"  << endl;

	float *d_pqTable = NULL;
	unsigned  *d_chunksOffset = NULL;
	float *d_centroid = NULL;

	gpuErrchk(cudaMalloc(&d_pqTable, sizeof(float) * (256*objIndexLoad.D)));
	gpuErrchk(cudaMalloc(&d_chunksOffset, sizeof(unsigned) * (n_chunks+1)));
	gpuErrchk(cudaMalloc(&d_centroid, sizeof(float) * (objIndexLoad.D)));			
	gpuErrchk(cudaMemcpy(d_centroid, centroid, sizeof(float) * (objIndexLoad.D), cudaMemcpyHostToDevice));

	objIndexLoad.d_pqTable = d_pqTable;
	objIndexLoad.d_chunksOffset = d_chunksOffset;
	objIndexLoad.d_centroid = d_centroid;

	// transpose pqTable
	float *pqTable_T = NULL; // always float irrespective of T
	pqTable_T = (float*) malloc(sizeof(float) * (256 * objIndexLoad.D));
	for(unsigned row = 0; row < 256; ++row) {
		for(unsigned col = 0; col < objIndexLoad.D; ++col) {
			pqTable_T[col* 256 + row] = pqTable[row*objIndexLoad.D+col];
		}
	}

	// host to device transfer
	gpuErrchk(cudaMemcpy(d_pqTable, pqTable_T, sizeof(float) * (256*objIndexLoad.D), cudaMemcpyHostToDevice));
	gpuErrchk(cudaMemcpy(d_chunksOffset, chunksOffset, sizeof(unsigned) * (n_chunks+1), cudaMemcpyHostToDevice));
	

	free(pqTable_T);
	pqTable_T = NULL;
	free(chunksOffset);
	chunksOffset = NULL;
	free(centroid);
	centroid = NULL;
}

template void bang_load<float>(char* );
template void bang_load<uint8_t>(char* );
}